### ISSUE TITLE
Unknown error code (453)

### ISSUE THREAD

**Issue by minisix** [dvargas92495/roamjs-twitter#11]
Error message while send Tweet: Unknown error code (453) . Setting up the account is all right. Where is the problem, please advise, thank you
![-132512](https://github.com/dvargas92495/roamjs-twitter/assets/13805824/6c1ccfd4-1af3-4ece-b158-0afcc0a232d3)

**Comment by dvargasfuertes** [comment]
Known issue - Twitter cut off our access on April 14th: https://github.com/samepage-network/samepage.network/issues/65
