### ISSUE TITLE
Login failed with 401

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-twitter#9]
`Request failed with status code 401`

![image](https://github.com/dvargas92495/roamjs-twitter/assets/3792666/0b7d7b5a-32f1-4fa9-9ef1-0a09f52d9aae)

From: https://roamresearch.slack.com/archives/C03QMNFE11S/p1685169963470469

**Comment by dvargasfuertes** [comment]
Duplicate with https://github.com/samepage-network/samepage.network/issues/65
